// Generated by scripts/download-cloud-photos.mjs — do not edit by hand.
// Photos: Flickr photographers via Openverse, CC0 / Public Domain Mark / CC BY / CC BY-SA.
// See scripts/cloud-photos.json.
import type { CloudImage } from './cloudImageTypes';

export const CLOUD_IMAGES: Record<string, CloudImage[]> = {
  "altocumulus": [
    { source: require('../../assets/clouds/altocumulus-1.jpg'), credit: {"author":"brownpau","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/44124483743@N01/10809845126"} },
    { source: require('../../assets/clouds/altocumulus-2.jpg'), credit: {"author":"JOHN K THORNE","license":"CC0","sourceUrl":"https://www.flickr.com/photos/89918055@N05/51589808330"} },
    { source: require('../../assets/clouds/altocumulus-3.jpg'), credit: {"author":"albategnius","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/42914481@N00/9653764371"} },
  ],
  "altocumulus-castellanus": [
    { source: require('../../assets/clouds/altocumulus-castellanus-1.jpg'), credit: {"author":"abcdrizzle","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/194669275@N02/51978476752"} },
    { source: require('../../assets/clouds/altocumulus-castellanus-2.jpg'), credit: {"author":"abcdrizzle","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/194669275@N02/51979980839"} },
    { source: require('../../assets/clouds/altocumulus-castellanus-3.jpg'), credit: {"author":"Daniele Brundu","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/65728876@N03/23526405021"} },
  ],
  "altocumulus-floccus": [
    { source: require('../../assets/clouds/altocumulus-floccus-1.jpg'), credit: {"author":"abcdrizzle","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/194669275@N02/51980712708"} },
    { source: require('../../assets/clouds/altocumulus-floccus-2.jpg'), credit: {"author":"abcdrizzle","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/194669275@N02/52067646224"} },
  ],
  "altocumulus-lenticularis": [
    { source: require('../../assets/clouds/altocumulus-lenticularis-1.jpg'), credit: {"author":"joiseyshowaa","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/30201239@N00/43381939781"} },
    { source: require('../../assets/clouds/altocumulus-lenticularis-2.jpg'), credit: {"author":"fdecomite","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/21649179@N00/9789225826"} },
    { source: require('../../assets/clouds/altocumulus-lenticularis-3.jpg'), credit: {"author":"gull@cyberspace.org","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/22426639@N06/6170575627"} },
  ],
  "altostratus": [
    { source: require('../../assets/clouds/altostratus-1.jpg'), credit: {"author":"muffinn","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/26445715@N00/6648050691"} },
    { source: require('../../assets/clouds/altostratus-2.jpg'), credit: {"author":"Daniele Brundu","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/65728876@N03/26398556034"} },
    { source: require('../../assets/clouds/altostratus-3.jpg'), credit: {"author":"Daniele Brundu","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/65728876@N03/26398876664"} },
  ],
  "arcus": [
    { source: require('../../assets/clouds/arcus-1.jpg'), credit: {"author":"otrow_photography","license":"CC0","sourceUrl":"https://www.flickr.com/photos/183939796@N07/50772162733"} },
    { source: require('../../assets/clouds/arcus-2.jpg'), credit: {"author":"otrow_photography","license":"CC0","sourceUrl":"https://www.flickr.com/photos/183939796@N07/50152797196"} },
    { source: require('../../assets/clouds/arcus-3.jpg'), credit: {"author":"chief_huddleston","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/9265232@N04/4739552772"} },
  ],
  "asperitas": [
    { source: require('../../assets/clouds/asperitas-1.jpg'), credit: {"author":"James Loesch","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/34920192@N02/52037390104"} },
    { source: require('../../assets/clouds/asperitas-2.jpg'), credit: {"author":"James Loesch","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/34920192@N02/52037655695"} },
    { source: require('../../assets/clouds/asperitas-3.jpg'), credit: {"author":"Peter O'Connor aka anemoneprojectors","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/58414938@N00/51536586120"} },
  ],
  "cirrocumulus": [
    { source: require('../../assets/clouds/cirrocumulus-1.jpg'), credit: {"author":"Joshua Tree National Park","license":"Public domain","sourceUrl":"https://www.flickr.com/photos/115357548@N08/16006736963"} },
    { source: require('../../assets/clouds/cirrocumulus-2.jpg'), credit: {"author":"prof.bizzarro","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/58144587@N02/17541966284"} },
    { source: require('../../assets/clouds/cirrocumulus-3.jpg'), credit: {"author":"brownpau","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/44124483743@N01/4322332298"} },
  ],
  "cirrostratus": [
    { source: require('../../assets/clouds/cirrostratus-1.jpg'), credit: {"author":"emarquetti","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/94408930@N00/65891608"} },
    { source: require('../../assets/clouds/cirrostratus-2.jpg'), credit: {"author":"brownpau","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/44124483743@N01/5640054547"} },
    { source: require('../../assets/clouds/cirrostratus-3.jpg'), credit: {"author":"brownpau","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/44124483743@N01/5142209603"} },
  ],
  "cirrus": [
    { source: require('../../assets/clouds/cirrus-1.jpg'), credit: {"author":"k4dordy","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/8593364@N06/2915278884"} },
    { source: require('../../assets/clouds/cirrus-2.jpg'), credit: {"author":"Wilson Hui","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/51942038@N04/16369018692"} },
    { source: require('../../assets/clouds/cirrus-3.jpg'), credit: {"author":"Mullica","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/8561516@N08/5167599860"} },
  ],
  "cirrus-spissatus": [
    { source: require('../../assets/clouds/cirrus-spissatus-1.jpg'), credit: {"author":"fdecomite","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/21649179@N00/264134708"} },
    { source: require('../../assets/clouds/cirrus-spissatus-2.jpg'), credit: {"author":"Daniele Brundu","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/65728876@N03/27186461730"} },
    { source: require('../../assets/clouds/cirrus-spissatus-3.jpg'), credit: {"author":"abcdrizzle","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/194669275@N02/51979863224"} },
  ],
  "cirrus-uncinus": [
    { source: require('../../assets/clouds/cirrus-uncinus-1.jpg'), credit: {"author":"James St. John","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/47445767@N05/49904839006"} },
    { source: require('../../assets/clouds/cirrus-uncinus-2.jpg'), credit: {"author":"James St. John","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/47445767@N05/22859351903"} },
    { source: require('../../assets/clouds/cirrus-uncinus-3.jpg'), credit: {"author":"robhogg68","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/81515232@N07/7472664882"} },
  ],
  "contrail": [
    { source: require('../../assets/clouds/contrail-1.jpg'), credit: {"author":"James Loesch","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/34920192@N02/16138668141"} },
    { source: require('../../assets/clouds/contrail-2.jpg'), credit: {"author":"emdot","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/35237093637@N01/99251945"} },
    { source: require('../../assets/clouds/contrail-3.jpg'), credit: {"author":"blachswan","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/40883175@N06/14561575238"} },
  ],
  "cumulonimbus": [
    { source: require('../../assets/clouds/cumulonimbus-1.jpg'), credit: {"author":"thebadastronomer","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/80464810@N00/28103100291"} },
    { source: require('../../assets/clouds/cumulonimbus-2.jpg'), credit: {"author":"Flikkersteph -5,000,000 views ,thank you!","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/42741665@N08/8877119762"} },
    { source: require('../../assets/clouds/cumulonimbus-3.jpg'), credit: {"author":"FlickrdeChato","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/26641025@N07/3923538729"} },
  ],
  "cumulonimbus-calvus": [
    { source: require('../../assets/clouds/cumulonimbus-calvus-1.jpg'), credit: {"author":"jimmy_tst","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/59895673@N06/18249059935"} },
    { source: require('../../assets/clouds/cumulonimbus-calvus-2.jpg'), credit: {"author":"abcdrizzle","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/194669275@N02/52221574475"} },
    { source: require('../../assets/clouds/cumulonimbus-calvus-3.jpg'), credit: {"author":"Nicholas_T","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/14922165@N00/5779406540"} },
  ],
  "cumulonimbus-incus": [
    { source: require('../../assets/clouds/cumulonimbus-incus-1.jpg'), credit: {"author":"Nicholas_T","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/14922165@N00/543334336"} },
    { source: require('../../assets/clouds/cumulonimbus-incus-2.jpg'), credit: {"author":"Mostly Dans","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/22541812@N03/4867035856"} },
    { source: require('../../assets/clouds/cumulonimbus-incus-3.jpg'), credit: {"author":"Seluryar","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/90403972@N00/14245225351"} },
  ],
  "cumulus": [
    { source: require('../../assets/clouds/cumulus-1.jpg'), credit: {"author":"moonjazz","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/8398907@N02/47981683236"} },
    { source: require('../../assets/clouds/cumulus-2.jpg'), credit: {"author":"jimmy_tst","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/59895673@N06/9083005126"} },
    { source: require('../../assets/clouds/cumulus-3.jpg'), credit: {"author":"joncandy","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/37195744@N03/9421862301"} },
  ],
  "cumulus-congestus": [
    { source: require('../../assets/clouds/cumulus-congestus-1.jpg'), credit: {"author":"James St. John","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/47445767@N05/28191827302"} },
    { source: require('../../assets/clouds/cumulus-congestus-2.jpg'), credit: {"author":"renee_mcgurk","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/51018933@N08/8329956077"} },
    { source: require('../../assets/clouds/cumulus-congestus-3.jpg'), credit: {"author":"renee_mcgurk","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/51018933@N08/5966639509"} },
  ],
  "cumulus-fractus": [
    { source: require('../../assets/clouds/cumulus-fractus-1.jpg'), credit: {"author":"altiemae","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/34065951@N08/14749917473"} },
    { source: require('../../assets/clouds/cumulus-fractus-2.jpg'), credit: {"author":"altiemae","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/34065951@N08/26750109282"} },
    { source: require('../../assets/clouds/cumulus-fractus-3.jpg'), credit: {"author":"altiemae","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/34065951@N08/8433619383"} },
  ],
  "cumulus-humilis": [
    { source: require('../../assets/clouds/cumulus-humilis-1.jpg'), credit: {"author":"abcdrizzle","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/194669275@N02/51979598116"} },
    { source: require('../../assets/clouds/cumulus-humilis-2.jpg'), credit: {"author":"abcdrizzle","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/194669275@N02/51979678563"} },
    { source: require('../../assets/clouds/cumulus-humilis-3.jpg'), credit: {"author":"the real Kam75","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/17739066@N00/4778467180"} },
  ],
  "cumulus-mediocris": [
    { source: require('../../assets/clouds/cumulus-mediocris-1.jpg'), credit: {"author":"atlnature","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/149638594@N05/49949023436"} },
    { source: require('../../assets/clouds/cumulus-mediocris-2.jpg'), credit: {"author":"abcdrizzle","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/194669275@N02/52287977184"} },
    { source: require('../../assets/clouds/cumulus-mediocris-3.jpg'), credit: {"author":"abcdrizzle","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/194669275@N02/51826861058"} },
  ],
  "fallstreak-hole": [
    { source: require('../../assets/clouds/fallstreak-hole-1.jpg'), credit: {"author":"Ozzy Delaney","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/24931020@N02/15533401437"} },
    { source: require('../../assets/clouds/fallstreak-hole-2.jpg'), credit: {"author":"Jeffrey Beall","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/31437555@N00/51522181419"} },
    { source: require('../../assets/clouds/fallstreak-hole-3.jpg'), credit: {"author":"puffin11uk","license":"CC0","sourceUrl":"https://www.flickr.com/photos/48125931@N00/8015649777"} },
  ],
  "fog": [
    { source: require('../../assets/clouds/fog-1.jpg'), credit: {"author":"fveronesi1","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/30818542@N04/50528816097"} },
    { source: require('../../assets/clouds/fog-2.jpg'), credit: {"author":"John-Morgan","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/24742305@N00/3072712788"} },
    { source: require('../../assets/clouds/fog-3.jpg'), credit: {"author":"HighTechDad","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/22473198@N00/31142787306"} },
  ],
  "funnel-cloud": [
    { source: require('../../assets/clouds/funnel-cloud-1.jpg'), credit: {"author":"sourtoe","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/26142070@N05/2454906745"} },
    { source: require('../../assets/clouds/funnel-cloud-2.jpg'), credit: {"author":"sponki25","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/147079914@N03/35671253072"} },
    { source: require('../../assets/clouds/funnel-cloud-3.jpg'), credit: {"author":"Elsie esq.","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/61132483@N00/4848360345"} },
  ],
  "kelvin-helmholtz": [
    { source: require('../../assets/clouds/kelvin-helmholtz-1.jpg'), credit: {"author":"fdecomite","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/21649179@N00/33301510804"} },
    { source: require('../../assets/clouds/kelvin-helmholtz-2.jpg'), credit: {"author":"Noel Feans","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/37563893@N00/40846169194"} },
    { source: require('../../assets/clouds/kelvin-helmholtz-3.jpg'), credit: {"author":"Danny Chapman","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/11152520@N03/8915858379"} },
  ],
  "mammatus": [
    { source: require('../../assets/clouds/mammatus-1.jpg'), credit: {"author":"eviltomthai","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/77516834@N00/3666079674"} },
    { source: require('../../assets/clouds/mammatus-2.jpg'), credit: {"author":"ghewgill","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/28923985@N00/2904685577"} },
    { source: require('../../assets/clouds/mammatus-3.jpg'), credit: {"author":"sponki25","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/147079914@N03/49521134183"} },
  ],
  "nacreous": [
    { source: require('../../assets/clouds/nacreous-1.jpg'), credit: {"author":"Alan R. Light","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/57202181@N05/5273198508"} },
    { source: require('../../assets/clouds/nacreous-2.jpg'), credit: {"author":"Alan R. Light","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/57202181@N05/5273234782"} },
    { source: require('../../assets/clouds/nacreous-3.jpg'), credit: {"author":"Alan R. Light","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/57202181@N05/5273213702"} },
  ],
  "nimbostratus": [
    { source: require('../../assets/clouds/nimbostratus-1.jpg'), credit: {"author":"oddharmonic","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/42528087@N00/2405697497"} },
    { source: require('../../assets/clouds/nimbostratus-2.jpg'), credit: {"author":"oddharmonic","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/42528087@N00/2236281652"} },
    { source: require('../../assets/clouds/nimbostratus-3.jpg'), credit: {"author":"oddharmonic","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/42528087@N00/2235491861"} },
  ],
  "noctilucent": [
    { source: require('../../assets/clouds/noctilucent-1.jpg'), credit: {"author":"Rab .","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/58739232@N07/48177440731"} },
    { source: require('../../assets/clouds/noctilucent-2.jpg'), credit: {"author":"timo_w2s","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/19935963@N00/14545524257"} },
    { source: require('../../assets/clouds/noctilucent-3.jpg'), credit: {"author":"Image Editor","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/11304375@N07/7008188265"} },
  ],
  "pileus": [
    { source: require('../../assets/clouds/pileus-1.jpg'), credit: {"author":"Angela Llop","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/37963111@N03/51498179579"} },
    { source: require('../../assets/clouds/pileus-2.jpg'), credit: {"author":"prof.bizzarro","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/58144587@N02/8044475699"} },
    { source: require('../../assets/clouds/pileus-3.jpg'), credit: {"author":"James St. John","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/47445767@N05/27680866044"} },
  ],
  "pyrocumulus": [
    { source: require('../../assets/clouds/pyrocumulus-1.jpg'), credit: {"author":"niiicedave","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/33671002@N00/15191360376"} },
    { source: require('../../assets/clouds/pyrocumulus-2.jpg'), credit: {"author":"bcgrote","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/8431864@N07/3881745498"} },
    { source: require('../../assets/clouds/pyrocumulus-3.jpg'), credit: {"author":"National Interagency Fire Center","license":"Public domain","sourceUrl":"https://www.flickr.com/photos/165415395@N07/54693672660"} },
  ],
  "roll-cloud": [
    { source: require('../../assets/clouds/roll-cloud-1.jpg'), credit: {"author":"versageek","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/8241297@N03/25765324160"} },
    { source: require('../../assets/clouds/roll-cloud-2.jpg'), credit: {"author":"leppre","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/46018179@N00/46099200302"} },
  ],
  "stratocumulus": [
    { source: require('../../assets/clouds/stratocumulus-1.jpg'), credit: {"author":"Tomasz Lewicki","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/46019229@N03/7330786536"} },
    { source: require('../../assets/clouds/stratocumulus-2.jpg'), credit: {"author":"Judy Gallagher","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/52450054@N04/15703519221"} },
    { source: require('../../assets/clouds/stratocumulus-3.jpg'), credit: {"author":"Gabriel Fr","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/132580358@N08/52593573261"} },
  ],
  "stratus": [
    { source: require('../../assets/clouds/stratus-1.jpg'), credit: {"author":"Storm Crypt","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/21366409@N00/3051911226"} },
    { source: require('../../assets/clouds/stratus-2.jpg'), credit: {"author":"mynameisharsha","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/27526538@N07/4901218525"} },
    { source: require('../../assets/clouds/stratus-3.jpg'), credit: {"author":"mynameisharsha","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/27526538@N07/4901797580"} },
  ],
  "virga": [
    { source: require('../../assets/clouds/virga-1.jpg'), credit: {"author":"snowpeak","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/53986933@N00/15034424411"} },
    { source: require('../../assets/clouds/virga-2.jpg'), credit: {"author":"bossco","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/43521640@N00/4077812549"} },
    { source: require('../../assets/clouds/virga-3.jpg'), credit: {"author":"Paul Garland","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/55922094@N00/3373962670"} },
  ],
  "wall-cloud": [
    { source: require('../../assets/clouds/wall-cloud-1.jpg'), credit: {"author":"Photography by Daniel Rodriguez","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/10256071@N04/8789258802"} },
    { source: require('../../assets/clouds/wall-cloud-2.jpg'), credit: {"author":"presgengardner","license":"CC BY-SA","sourceUrl":"https://www.flickr.com/photos/134386919@N03/18703163934"} },
    { source: require('../../assets/clouds/wall-cloud-3.jpg'), credit: {"author":"Photography by Daniel Rodriguez","license":"CC BY","sourceUrl":"https://www.flickr.com/photos/10256071@N04/7186883809"} },
  ],
};
